# DB Node names and formats
INGREDIENTS_NODE_REF = "ingredients"
INGREDIENTS_SUB_NODE_REF_FORMAT = "ingredients/{}"
INGREDIENT_SUB_NODE_UNIT_REF = "units"
INGREDIENTS_SUB_NODE_UNITS_REF_FORMAT = "ingredients/{}/" + INGREDIENT_SUB_NODE_UNIT_REF
INGREDIENTS_SUB_NODE_NAME_REF = "name"
INGREDIENT_SUB_NODE_CATEGORY_NAME = "category"
INGREDIENT_SUB_NODE_SUPERMARKET_REF = "supermarkets"
NEW_INGREDIENT_UNIT_REF = "units"
NEW_INGREDIENT_SUPERMARKET_REF = "supermarkets"

RECIPES_NODE_REF = "recipes"
RECIPES_SUB_NODE_NAME_REF = "name"
RECIPES_SUB_NODE_DESCRIPTION_REF = "description"
RECIPES_SUB_NODE_LINK_REF = "link"
RECIPES_SUB_NODE_REF_FORMAT = "recipes/{}"
RECIPE_INGREDIENT_UNIT_REF = "units"
RECIPE_INGREDIENT_QUANTITY_REF = "quantity"
RECIPE_INGREDIENT_SUPERMARKET_REF = "supermarkets"
RECIPE_SUB_NODE_INGREDIENTS_REF = "ingredients"
RECIPE_NEW_INGREDIENTS_REF = "new_ingredients"
RECIPE_IDS_REF = "recipes_ids"

UNITS_NODE_REF = "units"
NEW_UNIT_REF = "unit"

SUPERMARKETS_NODE_REF = "supermarkets"
NEW_SUPERMARKET_REF = "supermarkets"
SUPERMARKETS_SUB_NODE_REF_FORMAT = "supermarkets/{}"

GENERAL_ID_REF = "id"
